name: panteao
description: Dart client for the Panteao BDI Coprocessor. Integrates multi-agent BDI systems via JSON and Sockets natively in your Dart or Flutter application.
version: 1.1.17
environment:
  sdk: '>=3.0.0 <4.0.0'
repository: https://github.com/kkphoenixgx/aop-globalization
homepage: https://github.com/kkphoenixgx/aop-globalization/tree/main/sdk/dart
